import Navbar from "./components/Navbar";
import { Work_Sans } from "next/font/google";
import "./globals.css";

const workSans = Work_Sans({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  display: "swap",
});

export const metadata = {
  title: "Fallow",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* Apply the Work Sans font globally */}
      <body className={`${workSans.className}`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
